### ISSUE TITLE
Memory operands 1 extension references the EXTEN control register which is no longer present

### ISSUE THREAD

**Issue by EnderShadow** [ETC-A/etca-spec#18]
https://github.com/ETC-A/etca-spec/tree/main/extensions/memory-operands-1#d8-and-dp

This will need to be fixed when we draft the larger address space extensions

**Comment by JKTKops** [comment]
Those extensions will need to provide some (privileged) mechanism for changing the addressing mode. Previously the way we planned on having that work was writing to EXTEN.

**Comment by EnderShadow** [comment]
Definitely. I was thinking of a similar privileged CR for handling it.
