### ISSUE TITLE
calling convention for sN registers of REX

### ISSUE THREAD

**Issue by Ezra** [ETC-A/etca-spec#20]
Commit 7f66dbe updates the documentation of the [Expanded Registers](https://github.com/ETC-A/etca-spec/blob/main/extensions/expanded-registers) extension, to the current names for the added registers. I think its "who saves it" column may need an update to match.

Formerly, the registers r13-r15 had aliases a8, t0, and t1, and correspondingly were listed as call**er**-saved. Register aliases s2-s4 were on registers r24-r26, and were call**ee**-saved. Now r13-r15 _are_ s2-s4, but they've kept their call**er**-saved recommendation, which seems inconsistent with the caption text that "sN registers are registers that must be saved before re-using."

Should they be updated to call**ee**-saved, like the other sN registers? Or is it intended that these registers keep the call**er**-saved status?

**Comment by Ezra** [comment]
Some asides:
- This is tricky to catch because of the visual similarity of the words "caller" and "callee." One way to make the column clearer would be to change the "who saves it" column to (a "calling convention" column with entries of) ["call-clobbered" and "call-preserved"](https://stackoverflow.com/questions/9268586/what-are-callee-and-caller-saved-registers).
- The table key mentions aN registers, but the current version doesn't add any aN registers.
- We could cross-link the mention of the [Stack & Functions](https://github.com/ETC-A/etca-spec/blob/main/extensions/stack-and-functions) extension. Might also be worth linking back here from its key's tN entry, since the base Stack & Functions doesn't declare any of those.  
- The article could be a bit clearer about "must" and "should". It says you *must* save sN registers before reusing them, but also that the calling convention is just a suggestion.

I plan to put together a quick PR against this issue, with my suggested changes.

**Comment by EnderShadow** [comment]
Yeah, there were a few things that got missed when we changed the extension so it only provided 16 total registers.

**Comment by EnderShadow** [comment]
Resolved by #24
