### ISSUE TITLE
Optionally Allow REX.Q for MO2 instructions with both displacements and immediates

### ISSUE THREAD

**Issue by RicardoLuis0** [ETC-A/etca-spec#29]
While it's not easily implementable in every CPU design, for others it's simple to support the instruction size required for 9 bytes (8 disp + 1 imm) or even 16 bytes (8 disp + 8 imm) of displacement/immediate in MO2, so it'd be great if it wasn't required to be an illegal instruction in those cases.

**Comment by EnderShadow** [comment]
I'm all for relaxing the restriction so that you can do `8 disp + 1 imm` or `1 disp + 8 imm`, but allowing `8 disp + 8 imm` would require more thought since we're effectively allowing 2 expanded register prefixes in a single instruction. And in that case, we'd probably want to allow any combination of `1, 2, 4, 8 disp + 1, 2, 4, 8 imm` which would require specifying an order to 2 expanded register prefixes as well. That's ignoring the fact that we'd be opening ourselves up to either needing to support 32 registers through the ABX bits on both prefixes or choosing which prefix takes precedence over the other.

**Comment by RicardoLuis0** [comment]
`8 disp + 8 imm` is simple by just sharing the Q flag with both the disp and imm, so, ex. qword addressing, SS=11 Q=0 would be `4 disp + 4 imm`, and SS=11 Q=1 would be `8 disp + 8 imm`, but there wouldn't be a way to allow `4 disp + 8 imm` that way

**Comment by EnderShadow** [comment]
Based on previous discussion in discord, I think we'll add a feature which allows `REX.Q` in situations where an 8 byte displacement + 1, 2, 4 byte immediate is needed, where an 8 byte immediate + 1, 2, 4 byte displacement is needed, and possibly where an 8 byte displacement + 8 byte immediate is needed.

**Comment by RicardoLuis0** [comment]
don't forget about `REX.A` being unused in the MO2 instructions with both displacements and immediates (since they don't use the `A` register), so it could be used to extend the immediate and dispalcement separately without adding an extra prefix

**Comment by EnderShadow** [comment]
That's incorrect. an RMI byte of `AAA 101 01` uses the A register, a sized immediate, and a sized displacement and thus may need the REX.A bit while not having enough bits to define a size for both the immediate and displacement.

Using REX.A or REX.B based on the instruction could work, but it would add too much complexity and thus I don't think it's worth discussion.

**Comment by EnderShadow** [comment]
Actually since all of this would involve changing instruction lengths from decoding, it would need to be as an extension rather than a feature I think.

**Comment by RicardoLuis0** [comment]
> That's incorrect. an RMI byte of `AAA 101 01` uses the A register, a sized immediate, and a sized displacement and thus may need the REX.A bit while not having enough bits to define a size for both the immediate and displacement.
> 
> Using REX.A or REX.B based on the instruction could work, but it would add too much complexity and thus I don't think it's worth discussion.

doesn't seem to be the case? it's [dP and **ip**](https://github.com/ETC-A/etca-spec/tree/main/extensions/memory-operands-2#:~:text=%2B%2D%2D%2D%2D%2D%2B%2D%2D%2D%2D%2D%2B%2D%2D%2D%2D%2B%0A%7C%20AAA%20%7C%20101,%5Bip%20%2B%20dP%5D), **not** dP and sP

**Comment by EnderShadow** [comment]
You're right. I forgot we had an IP relative addressing mode there. Either way, it would still be better as an extension since it modifies the length of an instruction.

**Comment by EnderShadow** [comment]
Also, this particular use-case is very odd. It's not likely to be used much if at all.

**Comment by EnderShadow** [comment]
Do you have a use case for this?

**Comment by RicardoLuis0** [comment]
no use case comes to mind right now, just thought it was worth mentioning that there's a spare bit in REX that's usable to allow extending iS and dP separately without requiring a second prefix

**Comment by EnderShadow** [comment]
In that case I'm going to shelve this issue for now.
